import { Header } from "@/components/header"
import { StepGuardToast } from "@/components/step-guard-toast"
import { ToastProvider } from "@/components/ui/toast"
import { Toaster } from "@/components/ui/toaster"
import { JourneyStoreProvider } from "@/providers/journey-store-provider"
import QueryClientProvider from "@/providers/query-client-provider"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Suspense } from "react"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <JourneyStoreProvider>
        <QueryClientProvider>
          <ToastProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased bg-red-500 min-h-screen`}
            >
              <Header />
              <main className="h-[calc(100vh-4rem)]">{children}</main>
              <Toaster />
              <Suspense>
                <StepGuardToast />
              </Suspense>
            </body>
          </ToastProvider>
        </QueryClientProvider>
      </JourneyStoreProvider>
    </html>
  )
}
